# Generated by Django 5.2.4 on 2025-10-29 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_initial"),
        ("posts", "0003_alter_postlike_post_alter_tag_slug_alter_tag_table"),
        ("social", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="comments.comment",
                        verbose_name="评论",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="posts.post",
                        verbose_name="帖子",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "点赞",
                "verbose_name_plural": "点赞",
                "indexes": [
                    models.Index(
                        fields=["user", "-created_at"],
                        name="social_like_user_id_323385_idx",
                    ),
                    models.Index(
                        fields=["post", "-created_at"],
                        name="social_like_post_id_f7b407_idx",
                    ),
                    models.Index(
                        fields=["comment", "-created_at"],
                        name="social_like_comment_bd7d22_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("post__isnull", False),
                            ("comment__isnull", False),
                            _connector="OR",
                        ),
                        name="like_post_or_comment",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("post__isnull", False)),
                        fields=("user", "post"),
                        name="unique_user_post_like",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("comment__isnull", False)),
                        fields=("user", "comment"),
                        name="unique_user_comment_like",
                    ),
                ],
            },
        ),
    ]
