# Generated by Django 5.2.4 on 2025-11-06 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="社区名称")),
                (
                    "slug",
                    models.SlugField(
                        max_length=220, unique=True, verbose_name="URL别名"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "cover_url",
                    models.URLField(blank=True, null=True, verbose_name="封面图片URL"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("interest", "兴趣爱好"),
                            ("city", "城市"),
                            ("oncampus", "校园"),
                            ("study_group", "学习小组"),
                        ],
                        default="interest",
                        max_length=20,
                        verbose_name="分类",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="城市"
                    ),
                ),
                (
                    "is_oncampus",
                    models.BooleanField(default=False, verbose_name="是否校园社区"),
                ),
                (
                    "is_study_group",
                    models.BooleanField(default=False, verbose_name="是否学习小组"),
                ),
                (
                    "members",
                    models.PositiveIntegerField(default=0, verbose_name="成员数"),
                ),
                (
                    "activity_rate",
                    models.FloatField(default=0.0, verbose_name="活跃度 0-1"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_communities",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "社区",
                "verbose_name_plural": "社区",
                "ordering": ["-members", "-activity_rate"],
            },
        ),
        migrations.CreateModel(
            name="CommunityMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "joined_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="加入时间"),
                ),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="communities.community",
                        verbose_name="社区",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="community_memberships",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "社区成员",
                "verbose_name_plural": "社区成员",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(
                fields=["category", "-members"], name="communities_categor_6c2a8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="community",
            index=models.Index(fields=["city"], name="communities_city_0e19a8_idx"),
        ),
        migrations.AddIndex(
            model_name="communitymember",
            index=models.Index(
                fields=["user", "community"], name="communities_user_id_a93a0e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="communitymember",
            unique_together={("user", "community")},
        ),
    ]
