# Generated by Django 5.2.4 on 2025-11-06 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("posts", "0003_alter_postlike_post_alter_tag_slug_alter_tag_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="学院名称"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        max_length=220, unique=True, verbose_name="URL别名"
                    ),
                ),
                (
                    "icon_url",
                    models.URLField(blank=True, null=True, verbose_name="图标URL"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "major_count",
                    models.PositiveIntegerField(default=0, verbose_name="专业数量"),
                ),
                (
                    "topic_count",
                    models.PositiveIntegerField(default=0, verbose_name="话题数量"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "学院",
                "verbose_name_plural": "学院",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Forum",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="名称"),
                ),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "论坛",
                "verbose_name_plural": "论坛",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览数"),
                ),
                (
                    "replies_count",
                    models.PositiveIntegerField(default=0, verbose_name="回复数"),
                ),
                ("is_pinned", models.BooleanField(default=False, verbose_name="置顶")),
                (
                    "is_solved",
                    models.BooleanField(default=False, verbose_name="已解决"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="作者",
                    ),
                ),
                (
                    "forum",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="forums.forum",
                        verbose_name="所属论坛",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, to="posts.tag", verbose_name="标签"
                    ),
                ),
            ],
            options={
                "verbose_name": "话题",
                "verbose_name_plural": "话题",
                "ordering": ["-is_pinned", "-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["-is_pinned", "-updated_at"],
                        name="forums_topi_is_pinn_58855f_idx",
                    ),
                    models.Index(
                        fields=["forum", "-created_at"],
                        name="forums_topi_forum_i_1fcf8d_idx",
                    ),
                ],
            },
        ),
    ]
