# Generated by Django 5.2.7 on 2025-11-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_profile_bio_alter_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="career_goals",
            field=models.TextField(blank=True, verbose_name="职业目标"),
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.TextField(blank=True, verbose_name="兴趣领域（逗号分隔）"),
        ),
        migrations.AddField(
            model_name="profile",
            name="learning_preferences",
            field=models.JSONField(blank=True, default=dict, verbose_name="学习偏好"),
        ),
        migrations.AddField(
            model_name="profile",
            name="preferred_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="昵称/preferred称呼"),
        ),
    ]
