# Generated by Django 5.2.7 on 2025-11-02 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campus", "0002_universityresource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("course", "课程资料"),
                            ("regulation", "校规"),
                            ("announcement", "公告"),
                            ("post", "帖子"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="文档类型",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "source_url",
                    models.URLField(blank=True, null=True, verbose_name="来源URL"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_documents",
                        to="campus.university",
                        verbose_name="所属大学",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_ai_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传者",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI文档",
                "verbose_name_plural": "AI文档",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="块内容")),
                ("chunk_index", models.IntegerField(verbose_name="块序号")),
                (
                    "chunk_metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="块元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="ai.aidocument",
                        verbose_name="所属文档",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI文本块",
                "verbose_name_plural": "AI文本块",
                "ordering": ["document", "chunk_index"],
            },
        ),
        migrations.CreateModel(
            name="AIEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "embedding_vector",
                    models.JSONField(
                        help_text="临时使用JSON存储，后续迁移到pgvector",
                        verbose_name="向量数据",
                    ),
                ),
                (
                    "embedding_model",
                    models.CharField(
                        default="text-embedding-ada-002",
                        max_length=100,
                        verbose_name="嵌入模型",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "chunk",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="ai.aichunk",
                        verbose_name="所属文本块",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI向量嵌入",
                "verbose_name_plural": "AI向量嵌入",
            },
        ),
        migrations.CreateModel(
            name="AIQueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_text", models.TextField(verbose_name="查询文本")),
                ("response_text", models.TextField(verbose_name="响应文本")),
                (
                    "matched_chunks",
                    models.JSONField(
                        blank=True, default=list, verbose_name="匹配的文本块ID列表"
                    ),
                ),
                (
                    "response_time_ms",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="响应时间(毫秒)"
                    ),
                ),
                (
                    "is_helpful",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="是否有帮助"
                    ),
                ),
                (
                    "feedback_text",
                    models.TextField(blank=True, verbose_name="用户反馈"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="查询时间"),
                ),
                (
                    "university",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_queries",
                        to="campus.university",
                        verbose_name="关联大学",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_queries",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="查询用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI查询日志",
                "verbose_name_plural": "AI查询日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="aidocument",
            index=models.Index(
                fields=["university", "doc_type"], name="ai_aidocume_univers_d7fecf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aidocument",
            index=models.Index(
                fields=["is_active", "-created_at"],
                name="ai_aidocume_is_acti_fbf6cf_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aichunk",
            index=models.Index(
                fields=["document", "chunk_index"], name="ai_aichunk_documen_c2f18f_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="aichunk",
            unique_together={("document", "chunk_index")},
        ),
        migrations.AddIndex(
            model_name="aiembedding",
            index=models.Index(
                fields=["created_at"], name="ai_aiembedd_created_636f62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiquerylog",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_aiqueryl_user_id_499e7b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiquerylog",
            index=models.Index(
                fields=["university", "-created_at"],
                name="ai_aiqueryl_univers_525b8c_idx",
            ),
        ),
    ]
