# Generated by Django 5.2.7 on 2025-11-15 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0001_initial"),
        ("campus", "0002_universityresource"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="aiquerylog",
            index=models.Index(
                fields=["-created_at"], name="ai_aiqueryl_created_e35abd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiquerylog",
            index=models.Index(
                fields=["user", "university", "-created_at"],
                name="ai_aiqueryl_user_id_64429b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="aiquerylog",
            index=models.Index(
                fields=["response_time_ms"], name="ai_aiqueryl_respons_951625_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiquerylog",
            index=models.Index(
                fields=["is_helpful", "-created_at"],
                name="ai_aiqueryl_is_help_27a5fd_idx",
            ),
        ),
    ]
