# Generated by Django 5.2.7 on 2025-11-23 09:23

import pgvector.django.vector
from django.db import migrations, models
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0003_aiconversation_aimessage_and_more"),
    ]

    operations = [
        # 1. 先删除原来的 JSONField 列
        migrations.RemoveField(
            model_name='aiembedding',
            name='embedding_vector',
        ),
        # 2. 再新增一个 pgvector 的列（同名）
        migrations.AddField(
            model_name='aiembedding',
            name='embedding_vector',
            field=pgvector.django.VectorField(
                dimensions=1536,
                verbose_name='向量数据',
                help_text='使用 pgvector 存储的向量',
                null=True,
                blank=True,
            ),
        ),
    ]
