# Generated by Django 5.2.7 on 2025-11-23 11:17

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0004_alter_aiembedding_embedding_vector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiembedding",
            name="embedding_model",
            field=models.CharField(
                default="nomic-embed-text", max_length=100, verbose_name="嵌入模型"
            ),
        ),
        migrations.AlterField(
            model_name="aiembedding",
            name="embedding_vector",
            field=pgvector.django.vector.VectorField(
                blank=True,
                dimensions=768,
                help_text="使用 pgvector 存储的向量",
                null=True,
                verbose_name="向量数据",
            ),
        ),
    ]
