# Generated by Django 5.2.7 on 2025-11-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0005_alter_aiembedding_embedding_model_and_more"),
        ("ai", "0006_enable_pgvector"),
    ]

    operations = []
