# Generated by Django 5.2.7 on 2025-11-30 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0007_merge_20251124_0105"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="aiconversation",
            name="context_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="用户画像、偏好等信息",
                verbose_name="上下文元数据",
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="context_summary",
            field=models.TextField(
                blank=True, help_text="会话上下文的压缩摘要", verbose_name="上下文摘要"
            ),
        ),
        migrations.AddField(
            model_name="aiconversation",
            name="total_tokens",
            field=models.IntegerField(
                default=0, help_text="当前会话使用的总token数", verbose_name="累计Token数"
            ),
        ),
        migrations.AlterField(
            model_name="aidocument",
            name="doc_type",
            field=models.CharField(
                choices=[
                    ("course", "课程资料"),
                    ("regulation", "校规"),
                    ("announcement", "公告"),
                    ("post", "帖子"),
                    ("resume", "简历模板"),
                    ("business_plan", "BP模板"),
                    ("company", "公司信息"),
                    ("market_report", "市场报告"),
                    ("salary", "薪资数据"),
                    ("other", "其他"),
                ],
                max_length=20,
                verbose_name="文档类型",
            ),
        ),
        migrations.CreateModel(
            name="AIRoutingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.TextField(verbose_name="用户查询")),
                ("recognized_function", models.CharField(max_length=50, verbose_name="识别的功能")),
                (
                    "confidence",
                    models.FloatField(help_text="识别置信度 0.0-1.0", verbose_name="置信度"),
                ),
                (
                    "method",
                    models.CharField(
                        help_text="mode, keyword, semantic, llm, default",
                        max_length=20,
                        verbose_name="识别方法",
                    ),
                ),
                (
                    "reasoning",
                    models.TextField(
                        blank=True, help_text="为什么选择这个功能", verbose_name="推理过程"
                    ),
                ),
                (
                    "manual_mode",
                    models.CharField(
                        blank=True,
                        help_text="如果用户手动指定mode，记录在此",
                        max_length=50,
                        verbose_name="手动指定模式",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(
                        blank=True,
                        help_text="后续人工标注或用户反馈",
                        null=True,
                        verbose_name="是否正确",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI路由日志",
                "verbose_name_plural": "AI路由日志",
                "db_table": "ai_routing_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["-created_at"], name="ai_routing__created_cb813b_idx"),
                    models.Index(
                        fields=["recognized_function", "-created_at"],
                        name="ai_routing__recogni_ddb341_idx",
                    ),
                    models.Index(
                        fields=["method", "-created_at"], name="ai_routing__method_98eca1_idx"
                    ),
                    models.Index(fields=["confidence"], name="ai_routing__confide_e3e552_idx"),
                    models.Index(
                        fields=["user", "-created_at"], name="ai_routing__user_id_f36f30_idx"
                    ),
                ],
            },
        ),
    ]
