# Generated by Django 5.2.7 on 2025-10-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, unique=True, verbose_name="大学名称"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                ("country", models.CharField(max_length=100, verbose_name="国家")),
                ("city", models.CharField(max_length=100, verbose_name="城市")),
                (
                    "logo",
                    models.URLField(blank=True, null=True, verbose_name="Logo URL"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="官网"),
                ),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "students_count",
                    models.PositiveIntegerField(default=0, verbose_name="学生数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "大学",
                "verbose_name_plural": "大学",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="学院名称")),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True, verbose_name="简介")),
                (
                    "students_count",
                    models.PositiveIntegerField(default=0, verbose_name="学生数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schools",
                        to="campus.university",
                        verbose_name="所属大学",
                    ),
                ),
            ],
            options={
                "verbose_name": "学院",
                "verbose_name_plural": "学院",
                "ordering": ["university", "name"],
                "unique_together": {("university", "name")},
            },
        ),
    ]
