# Generated by Django 5.2.7 on 2025-11-02 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campus", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UniversityResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("course", "课程"),
                            ("canteen", "食堂"),
                            ("club", "社团"),
                            ("event", "活动"),
                            ("notice", "通知"),
                        ],
                        max_length=20,
                        verbose_name="类别",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="标题")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "extra",
                    models.JSONField(
                        blank=True, default=dict, null=True, verbose_name="额外信息"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="是否启用"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="campus.university",
                        verbose_name="所属大学",
                    ),
                ),
            ],
            options={
                "verbose_name": "大学资源",
                "verbose_name_plural": "大学资源",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["university", "category"],
                        name="campus_univ_univers_cc3a67_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="campus_univ_is_acti_d8c4b7_idx",
                    ),
                ],
            },
        ),
    ]
