# Generated by Django 5.2.7 on 2025-10-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "收藏",
                "verbose_name_plural": "收藏",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=200, verbose_name="标题"),
                ),
                ("body", models.TextField(verbose_name="内容")),
                (
                    "image_url",
                    models.URLField(blank=True, null=True, verbose_name="图片链接"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "公开"),
                            ("followers", "仅关注者"),
                            ("university", "同校可见"),
                            ("private", "私密"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="可见性",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="已发布"),
                ),
                (
                    "likes_count",
                    models.PositiveIntegerField(default=0, verbose_name="点赞数"),
                ),
                (
                    "comments_count",
                    models.PositiveIntegerField(default=0, verbose_name="评论数"),
                ),
                (
                    "bookmarks_count",
                    models.PositiveIntegerField(default=0, verbose_name="收藏数"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "帖子",
                "verbose_name_plural": "帖子",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "帖子点赞",
                "verbose_name_plural": "帖子点赞",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, unique=True, verbose_name="标签名"),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "posts_count",
                    models.PositiveIntegerField(default=0, verbose_name="帖子数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "标签",
                "verbose_name_plural": "标签",
                "ordering": ["-posts_count", "name"],
            },
        ),
    ]
