# Generated by Django 5.2.4 on 2025-10-29 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postlike",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_likes",
                to="posts.post",
                verbose_name="帖子",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(blank=True, default="", max_length=60, unique=True),
        ),
        migrations.AlterModelTable(
            name="tag",
            table="posts_tag",
        ),
    ]
