# Generated by Django 5.2.7 on 2025-10-28 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campus", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Internship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="职位名称")),
                ("company", models.CharField(max_length=200, verbose_name="公司名称")),
                ("description", models.TextField(verbose_name="职位描述")),
                ("location", models.CharField(max_length=200, verbose_name="地点")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("full_time", "全职"),
                            ("part_time", "兼职"),
                            ("internship", "实习"),
                            ("remote", "远程"),
                        ],
                        max_length=50,
                        verbose_name="类型",
                    ),
                ),
                (
                    "duration",
                    models.CharField(blank=True, max_length=100, verbose_name="时长"),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="申请截止日期"
                    ),
                ),
                ("requirements", models.TextField(blank=True, verbose_name="职位要求")),
                (
                    "salary_range",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="薪资范围"
                    ),
                ),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="申请链接"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "公开"),
                            ("university", "同校可见"),
                            ("private", "私密"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="可见性",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="已发布"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "实习机会",
                "verbose_name_plural": "实习机会",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="项目名称")),
                ("description", models.TextField(verbose_name="项目描述")),
                ("location", models.CharField(max_length=200, verbose_name="地点")),
                (
                    "duration",
                    models.CharField(blank=True, max_length=100, verbose_name="时长"),
                ),
                (
                    "deadline",
                    models.DateField(
                        blank=True, null=True, verbose_name="申请截止日期"
                    ),
                ),
                ("requirements", models.TextField(blank=True, verbose_name="申请要求")),
                (
                    "link",
                    models.URLField(blank=True, null=True, verbose_name="详情链接"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "公开"),
                            ("university", "同校可见"),
                            ("private", "私密"),
                        ],
                        default="public",
                        max_length=20,
                        verbose_name="可见性",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="已发布"),
                ),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="浏览数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "host_university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exchange_programs",
                        to="campus.university",
                        verbose_name="主办大学",
                    ),
                ),
            ],
            options={
                "verbose_name": "交换项目",
                "verbose_name_plural": "交换项目",
                "ordering": ["-created_at"],
            },
        ),
    ]
