# Generated by Django 5.2.7 on 2025-10-28 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("opportunities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangeprogram",
            name="posted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_exchanges",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布者",
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="posted_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posted_internships",
                to=settings.AUTH_USER_MODEL,
                verbose_name="发布者",
            ),
        ),
    ]
