# Generated by Django 5.2.4 on 2025-11-06 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangeprogram",
            name="applied_count",
            field=models.PositiveIntegerField(default=0, verbose_name="申请人数"),
        ),
        migrations.AddField(
            model_name="exchangeprogram",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="国家"
            ),
        ),
        migrations.AddField(
            model_name="exchangeprogram",
            name="cover_url",
            field=models.URLField(blank=True, null=True, verbose_name="封面图片URL"),
        ),
        migrations.AddField(
            model_name="exchangeprogram",
            name="gpa_min",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="最低GPA要求"
            ),
        ),
        migrations.AddField(
            model_name="exchangeprogram",
            name="lang_req",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="语言要求"
            ),
        ),
        migrations.AddField(
            model_name="exchangeprogram",
            name="rating_avg",
            field=models.FloatField(default=0.0, verbose_name="平均评分"),
        ),
        migrations.AddField(
            model_name="exchangeprogram",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, verbose_name="评分数量"),
        ),
        migrations.AddField(
            model_name="exchangeprogram",
            name="stipend",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="奖学金"
            ),
        ),
        migrations.AddField(
            model_name="exchangeprogram",
            name="tuition",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="学费"
            ),
        ),
    ]
