# Generated by Django 5.2.4 on 2025-11-06 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0003_exchangeprogram_applied_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="internship",
            name="applicants_count",
            field=models.PositiveIntegerField(default=0, verbose_name="申请人数"),
        ),
        migrations.AddField(
            model_name="internship",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="城市"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="国家"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="remote",
            field=models.BooleanField(default=False, verbose_name="是否远程"),
        ),
        migrations.AddField(
            model_name="internship",
            name="salary_max",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="最高薪资"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="salary_min",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="最低薪资"
            ),
        ),
        migrations.AddField(
            model_name="internship",
            name="skills",
            field=models.JSONField(blank=True, default=list, verbose_name="所需技能"),
        ),
        migrations.CreateModel(
            name="Startup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="项目名称")),
                ("org_name", models.CharField(max_length=200, verbose_name="组织名称")),
                ("description", models.TextField(verbose_name="项目描述")),
                (
                    "description_short",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="简短描述"
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="城市")),
                (
                    "country",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="国家"
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="标签"),
                ),
                (
                    "equity_min",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最低股权比例%"
                    ),
                ),
                (
                    "equity_max",
                    models.FloatField(
                        blank=True, null=True, verbose_name="最高股权比例%"
                    ),
                ),
                (
                    "contact_url",
                    models.URLField(blank=True, null=True, verbose_name="联系方式URL"),
                ),
                (
                    "followers_count",
                    models.PositiveIntegerField(default=0, verbose_name="关注人数"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posted_startups",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "创业机会",
                "verbose_name_plural": "创业机会",
                "ordering": ["-created_at"],
            },
        ),
    ]
