# Generated by Django 5.2.4 on 2025-11-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("opportunities", "0004_internship_applicants_count_internship_city_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exchangeprogram",
            name="is_urgent",
            field=models.BooleanField(default=False, verbose_name="是否即将截止"),
        ),
        migrations.AddField(
            model_name="exchangeprogram",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="官网链接"),
        ),
    ]
